# Generated by Django 6.1.1 on 2026-09-10 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('postgresql', 'PostgreSQL')], default='postgresql', max_length=32)),
                ('connection_status', models.CharField(choices=[('not_tested', 'Not tested'), ('connected', 'Connected'), ('failed', 'Failed')], default='not_tested', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_source', to='projects.project')),
            ],
        ),
    ]
