# Generated by Django 6.1.1 on 2026-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_sources",
            "0002_datasource_database_datasource_encrypted_password_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="last_connection_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
