# Generated by Django 6.1.1 on 2026-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configuring', 'Configuring'), ('building_catalog', 'Building catalog'), ('ready', 'Ready'), ('regenerating_catalog', 'Regenerating catalog'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
    ]
