# Generated by Django 6.1.1 on 2026-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="developer_mode",
            field=models.BooleanField(default=False),
        ),
    ]
